version: "3"
services:
  fluentd:
    #restart: always
    image: fluentd_colorv:v1.3
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5140:5140"
      - "8888:8888"
    volumes:
#      - /fluentd/log:/fluentd/log  选用根目录的目的为 link时 宿主机有效

      - /fluentd/log:/home/fluent
      - ./etc:/fluentd/etc