version: "3"
services:
  fluentd:
    #restart: always
    image: fluent/fluentd:v1.3-debian-onbuild
    ports:
      - "24224:24224"
      - "24224:24224/udp"

    volumes:
      - ~/bigdata/logs:/fluentd/log
      - ./etc:/fluentd/etc
#    environment:
#      - FLUENT_UID=0